In [1]:
import pandas as pd

In [2]:
iris=pd.read_csv('Iris.csv')

In [3]:
iris.shape

(150, 6)

In [4]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [5]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [6]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
iris.value_counts(iris["Species"])

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [9]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
stats=iris.groupby("Species")

In [11]:
stats.describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [12]:
stats.mean()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [13]:
stats.median()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.0,3.4,1.50,0.2
Iris-versicolor,75.5,5.9,2.8,4.35,1.3
Iris-virginica,125.5,6.5,3.0,5.55,2.0

In [14]:
stats["SepalLengthCm"].max()

Species
Iris-setosa        5.8
Iris-versicolor    7.0
Iris-virginica     7.9
Name: SepalLengthCm, dtype: float64

In [15]:
stats["PetalLengthCm"].min()

Species
Iris-setosa        1.0
Iris-versicolor    3.0
Iris-virginica     4.5
Name: PetalLengthCm, dtype: float64

In [16]:
iris_setosa=iris[iris["Species"]=="Iris-setosa"].drop(columns=["Species"])

In [17]:
iris_setosa.describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [18]:
iris_setosa.quantile(0.25)

Id               13.250
SepalLengthCm     4.800
SepalWidthCm      3.125
PetalLengthCm     1.400
PetalWidthCm      0.200
Name: 0.25, dtype: float64

In [19]:
iris_setosa.quantile(0.31)

Id               16.190
SepalLengthCm     4.819
SepalWidthCm      3.200
PetalLengthCm     1.400
PetalWidthCm      0.200
Name: 0.31, dtype: float64

In [20]:
iris_versicolor=iris[iris["Species"]=="Iris-versicolor"].drop(columns=["Species"])

In [21]:
iris_versicolor.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [22]:
iris_versicolor.min()

Id               51.0
SepalLengthCm     4.9
SepalWidthCm      2.0
PetalLengthCm     3.0
PetalWidthCm      1.0
dtype: float64

In [23]:
iris_versicolor.quantile(0.25)

Id               63.250
SepalLengthCm     5.600
SepalWidthCm      2.525
PetalLengthCm     4.000
PetalWidthCm      1.200
Name: 0.25, dtype: float64

In [24]:
iris_versicolor.quantile(0.31)

Id               66.190
SepalLengthCm     5.619
SepalWidthCm      2.619
PetalLengthCm     4.019
PetalWidthCm      1.300
Name: 0.31, dtype: float64

In [25]:
nba=pd.read_csv('nba.csv')

In [26]:
nba.shape

(457, 9)

In [27]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [28]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [29]:
nba.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [30]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [31]:
nba.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [32]:
nba["College"] = nba["College"].fillna(nba["College"].mode()[0])
nba["Salary"]=nba["Salary"].fillna(nba["Salary"].mean())

In [33]:
nba.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [41]:
weight=nba.groupby('Weight')

In [42]:
weight.describe()

       Number                                                   Age        \
        count  mean       std   min    25%   50%    75%   max count  mean
Weight
161.0     1.0   0.0       NaN   0.0   0.00   0.0   0.00   0.0   1.0  31.0
165.0     2.0  10.0  2.828427   8.0   9.00  10.0  11.00  12.0   2.0  23.0
169.0     1.0  55.0       NaN  55.0  55.00  55.0  55.00  55.0   1.0  26.0
170.0     1.0   2.0       NaN   2.0   2.00   2.0   2.00   2.0   1.0  25.0
172.0     2.0  19.5  3.535534  17.0  18.25  19.5  20.75  22.0   2.0  29.0
...       ...   ...       ...   ...    ...   ...    ...   ...   ...   ...
279.0     1.0   0.0       NaN   0.0   0.00   0.0   0.00   0.0   1.0  22.0
280.0     1.0  23.0       NaN  23.0  23.00  23.0  23.00  23.0   1.0  21.0
289.0     1.0  25.0       NaN  25.0  25.00  25.0  25.00  25.0   1.0  31.0
290.0     1.0  40.0       NaN  40.0  40.00  40.0  40.00  40.0   1.0  27.0
307.0     1.0  14.0       NaN  14.0  14.00  14.0  14.00  14.0   1.0  30.0

        ...             Salary                                          \
        ...   75%   max  count          mean           std         min
Weight  ...
161.0   ...  31.0  31.0    1.0  2.250000e+06           NaN   2250000.0
165.0   ...  23.0  23.0    2.0  2.771793e+06  2.928682e+06    700902.0
169.0   ...  26.0  26.0    1.0  8.344497e+06           NaN   8344497.0
170.0   ...  25.0  25.0    1.0  8.450590e+05           NaN    845059.0
172.0   ...  32.5  36.0    2.0  1.966932e+06  2.878384e+05   1763400.0
...     ...   ...   ...    ...           ...           ...         ...
279.0   ...  22.0  22.0    1.0  3.272091e+06           NaN   3272091.0
280.0   ...  21.0  21.0    1.0  1.842000e+06           NaN   1842000.0
289.0   ...  31.0  31.0    1.0  1.350000e+07           NaN  13500000.0
290.0   ...  27.0  27.0    1.0  1.200000e+06           NaN   1200000.0
307.0   ...  30.0  30.0    1.0  1.210000e+07           NaN  12100000.0


                 25%           50%           75%           max
Weight
161.0   2.250000e+06  2.250000e+06  2.250000e+06  2.250000e+06
165.0   1.736348e+06  2.771793e+06  3.807239e+06  4.842684e+06
169.0   8.344497e+06  8.344497e+06  8.344497e+06  8.344497e+06
170.0   8.450590e+05  8.450590e+05  8.450590e+05  8.450590e+05
172.0   1.865166e+06  1.966932e+06  2.068699e+06  2.170465e+06
...              ...           ...           ...           ...
279.0   3.272091e+06  3.272091e+06  3.272091e+06  3.272091e+06
280.0   1.842000e+06  1.842000e+06  1.842000e+06  1.842000e+06
289.0   1.350000e+07  1.350000e+07  1.350000e+07  1.350000e+07
290.0   1.200000e+06  1.200000e+06  1.200000e+06  1.200000e+06
307.0   1.210000e+07  1.210000e+07  1.210000e+07  1.210000e+07

[87 rows x 24 columns]

In [34]:
team=nba.groupby("Team")

In [35]:
team.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Kentucky,5.000000e+06
...,...,...,...,...,...,...,...,...,...
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4.775000e+06
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2.658240e+06
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9.463484e+06
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,Kentucky,3.777720e+06
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,1.200000e+07

In [36]:
team.describe()

                       Number                                                 \
                        count       mean        std  min    25%   50%    75%
Team
Atlanta Hawks            15.0  19.000000  11.476684  0.0  11.50  17.0  25.50
Boston Celtics           15.0  31.866667  30.300558  0.0   9.50  28.0  42.50
Brooklyn Nets            15.0  18.266667  14.104035  0.0   8.00  15.0  27.00
Charlotte Hornets        15.0  17.133333  16.672761  0.0   4.00  12.0  27.50
Chicago Bulls            15.0  19.200000  17.193022  0.0   5.50  16.0  28.00
Cleveland Cavaliers      15.0  14.466667  13.809245  0.0   4.50  12.0  21.50
Dallas Mavericks         15.0  20.000000  16.252472  1.0   6.00  21.0  30.50
Denver Nuggets           15.0  15.266667  19.655849  0.0   4.00   9.0  18.00
Detroit Pistons          15.0  17.266667  15.303906  0.0   5.50  13.0  23.50
Golden State Warriors    15.0  20.866667  11.413442  4.0  11.50  20.0  30.50
Houston Rockets          15.0  14.666667  12.505237  0.0   5.50  12.0  25.50
Indiana Pacers           15.0  18.933333  15.988686  0.0   4.00  13.0  30.50
Los Angeles Clippers     15.0  19.533333  13.125040  3.0   8.50  19.0  31.00
Los Angeles Lakers       15.0  16.066667  15.285225  0.0   3.50   9.0  26.00
Memphis Grizzlies        18.0  15.555556  14.030313  0.0   5.50  10.5  21.25
Miami Heat               15.0  10.466667  10.377632  0.0   3.50   8.0  13.00
Milwaukee Bucks          16.0  20.000000  17.485232  3.0  10.50  17.5  21.25
Minnesota Timberwolves   14.0  19.571429  21.964007  1.0   8.25  13.0  21.75
New Orleans Pelicans     19.0  17.000000  14.011900  0.0   4.50  15.0  27.50
New York Knicks          16.0  13.250000  12.964053  1.0   4.75   8.5  17.25
Oklahoma City Thunder    15.0  14.000000  12.130246  0.0   4.50  11.0  21.50
Orlando Magic            14.0  16.428571  16.411601  0.0   5.50  10.5  20.75
Philadelphia 76ers       15.0  18.066667  14.660280  0.0   6.00  12.0  32.00
Phoenix Suns             15.0  15.466667  10.405127  1.0   7.00  15.0  22.00
Portland Trail Blazers   15.0  16.000000  13.711309  0.0   4.50  11.0  23.50
Sacramento Kings         15.0  16.933333  12.002777  0.0   7.50  15.0  25.50
San Antonio Spurs        15.0  17.933333  11.067757  1.0  10.50  17.0  23.50
Toronto Raptors          15.0  22.466667  25.856380  1.0   5.50  10.0  27.50
Utah Jazz                15.0  17.866667  11.432202  2.0   9.00  20.0  24.50
Washington Wizards       15.0  17.600000  22.610996  1.0   5.50  12.0  19.00

                               Age             ...  Weight        Salary  \
                         max count       mean  ...     75%    max  count
Team                                           ...
Atlanta Hawks           43.0  15.0  28.200000  ...  242.50  260.0   15.0
Boston Celtics          99.0  15.0  24.733333  ...  236.50  260.0   15.0
Brooklyn Nets           44.0  15.0  25.600000  ...  220.50  275.0   15.0
Charlotte Hornets       50.0  15.0  26.133333  ...  240.00  289.0   15.0
Chicago Bulls           55.0  15.0  27.400000  ...  231.00  275.0   15.0
Cleveland Cavaliers     52.0  15.0  29.533333  ...  250.50  275.0   15.0
Dallas Mavericks        50.0  15.0  29.733333  ...  245.00  275.0   15.0
Denver Nuggets          77.0  15.0  25.733333  ...  226.50  280.0   15.0
Detroit Pistons         50.0  15.0  26.200000  ...  242.50  279.0   15.0
Golden State Warriors   40.0  15.0  27.666667  ...  247.50  273.0   15.0
Houston Rockets         35.0  15.0  26.866667  ...  237.50  265.0   15.0
Indiana Pacers          44.0  15.0  26.400000  ...  246.50  255.0   15.0
Los Angeles Clippers    45.0  15.0  29.466667  ...  242.50  265.0   15.0
Los Angeles Lakers      50.0  15.0  27.533333  ...  250.00  270.0   15.0
Memphis Grizzlies       50.0  18.0  28.388889  ...  236.75  270.0   18.0
Miami Heat              40.0  15.0  28.933333  ...  237.50  265.0   15.0
Milwaukee Bucks         77.0  16.0  24.562500  ...  246.75  265.0   16.0
Minnesota Timberwolves  88.0  14.0  26.357143  ...  240.75  307.0   14.0
New Orleans Pelicans    44.0  19.0  26.894737  ...  235.00  270.0   19.0
New York Knicks         43.0  16.0  27.000000  ...  240.00  278.0   16.0
Oklahoma City Thunder   35.0  15.0  27.066667  ...  247.50  255.0   15.0
Orlando Magic           55.0  14.0  25.071429  ...  238.75  260.0   14.0
Philadelphia 76ers      42.0  15.0  24.600000  ...  246.50  275.0   15.0
Phoenix Suns            35.0  15.0  25.866667  ...  241.00  260.0   15.0
Portland Trail Blazers  44.0  15.0  25.066667  ...  240.00  265.0   15.0
Sacramento Kings        41.0  15.0  26.800000  ...  239.00  270.0   15.0
San Antonio Spurs       40.0  15.0  31.600000  ...  245.00  290.0   15.0
Toronto Raptors         92.0  15.0  26.133333  ...  242.50  255.0   15.0
Utah Jazz               41.0  15.0  24.466667  ...  232.50  265.0   15.0
Washington Wizards      90.0  15.0  27.866667  ...  241.00  250.0   15.0

                                                                           \
                                mean           std        min         25%
Team
Atlanta Hawks           4.860197e+06  5.194508e+06   525093.0  1152260.00
Boston Celtics          4.225583e+06  3.036396e+06  1148640.0  1994760.00
Brooklyn Nets           3.501898e+06  5.317817e+06   134215.0   947276.00
Charlotte Hornets       5.222728e+06  4.538601e+06   189455.0  1543138.00
Chicago Bulls           5.785559e+06  6.251088e+06   525093.0  1203290.50
Cleveland Cavaliers     7.455425e+06  7.484116e+06   111196.0  1211638.00
Dallas Mavericks        4.746582e+06  5.030279e+06   525093.0  1185783.00
Denver Nuggets          4.330974e+06  4.165468e+06   258489.0  1647099.50
Detroit Pistons         4.477884e+06  4.668478e+06   111444.0  1711452.50
Golden State Warriors   5.924600e+06  5.664282e+06   289755.0  1201462.00
Houston Rockets         5.018868e+06  6.414749e+06   200600.0   973638.00
Indiana Pacers          4.450122e+06  4.584514e+06   211744.0  1053513.00
Los Angeles Clippers    6.323643e+06  7.600225e+06   111444.0  1024164.00
Los Angeles Lakers      4.784695e+06  6.835688e+06   525093.0   896167.50
Memphis Grizzlies       5.328979e+06  4.556591e+06   700902.0  1939075.00
Miami Heat              6.146736e+06  7.285680e+06   261894.0   947276.00
Milwaukee Bucks         4.350220e+06  4.875071e+06   295327.0  1483589.00
Minnesota Timberwolves  4.610884e+06  3.977783e+06   947276.0  1590540.00
New Orleans Pelicans    4.355304e+06  4.537874e+06    55722.0   981348.50
New York Knicks         4.581494e+06  5.952487e+06    30888.0   921721.75
Oklahoma City Thunder   6.251020e+06  6.632400e+06   222888.0  1742280.00
Orlando Magic           4.297248e+06  3.068412e+06   845059.0  2311302.00
Philadelphia 76ers      2.389039e+06  1.953024e+06   525093.0   947276.00
Phoenix Suns            4.229676e+06  5.022561e+06    55722.0   964312.00
Portland Trail Blazers  3.220121e+06  2.392741e+06   525093.0  1181398.00
Sacramento Kings        4.778911e+06  4.701792e+06   525093.0   998384.50
San Antonio Spurs       5.629516e+06  6.396804e+06   200600.0  1045078.00
Toronto Raptors         4.741174e+06  4.195943e+06   245177.0  1683000.00
Utah Jazz               4.204006e+06  4.467878e+06   900000.0  1262160.00
Washington Wizards      5.088576e+06  4.869388e+06   200600.0  1510421.00


                                 50%           75%         max
Team
Atlanta Hawks           2.854940e+06  6.873240e+06  18671659.0
Boston Celtics          3.425510e+06  5.898058e+06  12000000.0
Brooklyn Nets           1.335480e+06  2.512675e+06  19689000.0
Charlotte Hornets       4.204200e+06  6.665702e+06  13500000.0
Chicago Bulls           2.380440e+06  7.974380e+06  20093064.0
Cleveland Cavaliers     4.950000e+06  1.162482e+07  22970500.0
Dallas Mavericks        3.950313e+06  5.289487e+06  16407500.0
Denver Nuggets          3.000000e+06  4.593842e+06  14000000.0
Detroit Pistons         2.891760e+06  5.635000e+06  16000000.0
Golden State Warriors   3.815000e+06  1.154062e+07  15501000.0
Houston Rockets         2.288205e+06  7.339758e+06  22359364.0
Indiana Pacers          4.000000e+06  5.697112e+06  17120106.0
Los Angeles Clippers    3.110796e+06  8.367500e+06  21468695.0
Los Angeles Lakers      1.724250e+06  5.161144e+06  25000000.0
Memphis Grizzlies       4.842684e+06  5.387635e+06  19688000.0
Miami Heat              2.854940e+06  7.847668e+06  22192730.0
Milwaukee Bucks         2.254167e+06  5.514330e+06  16407500.0
Minnesota Timberwolves  3.049180e+06  5.744910e+06  12700000.0
New Orleans Pelicans    2.850000e+06  7.785365e+06  15514031.0
New York Knicks         2.225421e+06  4.949493e+06  22875000.0
Oklahoma City Thunder   3.344000e+06  8.694215e+06  20158622.0
Orlando Magic           3.956580e+06  5.144390e+06  11250000.0
Philadelphia 76ers      1.074169e+06  4.020240e+06   6500000.0
Phoenix Suns            2.041080e+06  5.500000e+06  13500000.0
Portland Trail Blazers  2.854940e+06  4.626144e+06   8042895.0
Sacramento Kings        3.156600e+06  6.880303e+06  15851950.0
San Antonio Spurs       2.814000e+06  8.750000e+06  19689000.0
Toronto Raptors         2.900000e+06  6.634338e+06  13600000.0
Utah Jazz               2.433333e+06  4.276360e+06  15409570.0
Washington Wizards      4.000000e+06  6.847337e+06  15851950.0

[30 rows x 32 columns]

In [37]:
team["Salary"].describe()

,count,mean,std,min,25%,50%,75%,max
Team,,,,,,,,
Atlanta Hawks,15.0,4.860197e+06,5.194508e+06,525093.0,1152260.00,2.854940e+06,6.873240e+06,18671659.0
Boston Celtics,15.0,4.225583e+06,3.036396e+06,1148640.0,1994760.00,3.425510e+06,5.898058e+06,12000000.0
Brooklyn Nets,15.0,3.501898e+06,5.317817e+06,134215.0,947276.00,1.335480e+06,2.512675e+06,19689000.0
Charlotte Hornets,15.0,5.222728e+06,4.538601e+06,189455.0,1543138.00,4.204200e+06,6.665702e+06,13500000.0
Chicago Bulls,15.0,5.785559e+06,6.251088e+06,525093.0,1203290.50,2.380440e+06,7.974380e+06,20093064.0
Cleveland Cavaliers,15.0,7.455425e+06,7.484116e+06,111196.0,1211638.00,4.950000e+06,1.162482e+07,22970500.0
Dallas Mavericks,15.0,4.746582e+06,5.030279e+06,525093.0,1185783.00,3.950313e+06,5.289487e+06,16407500.0
Denver Nuggets,15.0,4.330974e+06,4.165468e+06,258489.0,1647099.50,3.000000e+06,4.593842e+06,14000000.0
Detroit Pistons,15.0,4.477884e+06,4.668478e+06,111444.0,1711452.50,2.891760e+06,5.635000e+06,16000000.0
Golden State Warriors,15.0,5.924600e+06,5.664282e+06,289755.0,1201462.00,3.815000e+06,1.154062e+07,15501000.0
Houston Rockets,15.0,5.018868e+06,6.414749e+06,200600.0,973638.00,2.288205e+06,7.339758e+06,22359364.0
Indiana Pacers,15.0,4.450122e+06,4.584514e+06,211744.0,1053513.00,4.000000e+06,5.697112e+06,17120106.0
Los Angeles Clippers,15.0,6.323643e+06,7.600225e+06,111444.0,1024164.00,3.110796e+06,8.367500e+06,21468695.0
Los Angeles Lakers,15.0,4.784695e+06,6.835688e+06,525093.0,896167.50,1.724250e+06,5.161144e+06,25000000.0
Memphis Grizzlies,18.0,5.328979e+06,4.556591e+06,700902.0,1939075.00,4.842684e+06,5.387635e+06,19688000.0
Miami Heat,15.0,6.146736e+06,7.285680e+06,261894.0,947276.00,2.854940e+06,7.847668e+06,22192730.0
Milwaukee Bucks,16.0,4.350220e+06,4.875071e+06,295327.0,1483589.00,2.254167e+06,5.514330e+06,16407500.0
Minnesota Timberwolves,14.0,4.610884e+06,3.977783e+06,947276.0,1590540.00,3.049180e+06,5.744910e+06,12700000.0
New Orleans Pelicans,19.0,4.355304e+06,4.537874e+06,55722.0,981348.50,2.850000e+06,7.785365e+06,15514031.0
New York Knicks,16.0,4.581494e+06,5.952487e+06,30888.0,921721.75,2.225421e+06,4.949493e+06,22875000.0
Oklahoma City Thunder,15.0,6.251020e+06,6.632400e+06,222888.0,1742280.00,3.344000e+06,8.694215e+06,20158622.0
Orlando Magic,14.0,4.297248e+06,3.068412e+06,845059.0,2311302.00,3.956580e+06,5.144390e+06,11250000.0
Philadelphia 76ers,15.0,2.389039e+06,1.953024e+06,525093.0,947276.00,1.074169e+06,4.020240e+06,6500000.0
Phoenix Suns,15.0,4.229676e+06,5.022561e+06,55722.0,964312.00,2.041080e+06,5.500000e+06,13500000.0
Portland Trail Blazers,15.0,3.220121e+06,2.392741e+06,525093.0,1181398.00,2.854940e+06,4.626144e+06,8042895.0
Sacramento Kings,15.0,4.778911e+06,4.701792e+06,525093.0,998384.50,3.156600e+06,6.880303e+06,15851950.0
San Antonio Spurs,15.0,5.629516e+06,6.396804e+06,200600.0,1045078.00,2.814000e+06,8.750000e+06,19689000.0
Toronto Raptors,15.0,4.741174e+06,4.195943e+06,245177.0,1683000.00,2.900000e+06,6.634338e+06,13600000.0
Utah Jazz,15.0,4.204006e+06,4.467878e+06,900000.0,1262160.00,2.433333e+06,4.276360e+06,15409570.0
Washington Wizards,15.0,5.088576e+06,4.869388e+06,200600.0,1510421.00,4.000000e+06,6.847337e+06,15851950.0

In [38]:
team["Salary"].sum()

Team
Atlanta Hawks             7.290295e+07
Boston Celtics            6.338375e+07
Brooklyn Nets             5.252848e+07
Charlotte Hornets         7.834092e+07
Chicago Bulls             8.678338e+07
Cleveland Cavaliers       1.118314e+08
Dallas Mavericks          7.119873e+07
Denver Nuggets            6.496461e+07
Detroit Pistons           6.716826e+07
Golden State Warriors     8.886900e+07
Houston Rockets           7.528302e+07
Indiana Pacers            6.675183e+07
Los Angeles Clippers      9.485464e+07
Los Angeles Lakers        7.177043e+07
Memphis Grizzlies         9.592162e+07
Miami Heat                9.220104e+07
Milwaukee Bucks           6.960352e+07
Minnesota Timberwolves    6.455238e+07
New Orleans Pelicans      8.275077e+07
New York Knicks           7.330390e+07
Oklahoma City Thunder     9.376530e+07
Orlando Magic             6.016147e+07
Philadelphia 76ers        3.583558e+07
Phoenix Suns              6.344514e+07
Portland Trail Blazers    4.830182e+07
Sacramento Kings          7.168367e+07
San Antonio Spurs         8.444273e+07
Toronto Raptors           7.111761e+07
Utah Jazz                 6.306009e+07
Washington Wizards        7.632864e+07
Name: Salary, dtype: float64

In [39]:
team["Salary"].max()

Team
Atlanta Hawks             18671659.0
Boston Celtics            12000000.0
Brooklyn Nets             19689000.0
Charlotte Hornets         13500000.0
Chicago Bulls             20093064.0
Cleveland Cavaliers       22970500.0
Dallas Mavericks          16407500.0
Denver Nuggets            14000000.0
Detroit Pistons           16000000.0
Golden State Warriors     15501000.0
Houston Rockets           22359364.0
Indiana Pacers            17120106.0
Los Angeles Clippers      21468695.0
Los Angeles Lakers        25000000.0
Memphis Grizzlies         19688000.0
Miami Heat                22192730.0
Milwaukee Bucks           16407500.0
Minnesota Timberwolves    12700000.0
New Orleans Pelicans      15514031.0
New York Knicks           22875000.0
Oklahoma City Thunder     20158622.0
Orlando Magic             11250000.0
Philadelphia 76ers         6500000.0
Phoenix Suns              13500000.0
Portland Trail Blazers     8042895.0
Sacramento Kings          15851950.0
San Antonio Spurs         19689000.0
Toronto Raptors           13600000.0
Utah Jazz                 15409570.0
Washington Wizards        15851950.0
Name: Salary, dtype: float64

In [40]:
nba['Team'].unique()

array(['Boston Celtics', 'Brooklyn Nets', 'New York Knicks',
       'Philadelphia 76ers', 'Toronto Raptors', 'Golden State Warriors',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Phoenix Suns',
       'Sacramento Kings', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Detroit Pistons', 'Indiana Pacers', 'Milwaukee Bucks',
       'Dallas Mavericks', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Atlanta Hawks',
       'Charlotte Hornets', 'Miami Heat', 'Orlando Magic',
       'Washington Wizards', 'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz'],
      dtype=object)

In [44]:
nba["Age"].min()

19.0

In [45]:
nba["Age"].max()

40.0

In [46]:
bins = [19, 25, 31, 36, 40]
labels = ["Young adults", "Early adults", "Mid adults", "Mature adults"]

nba["AgeGroup"] = pd.cut(nba["Age"], bins=bins, labels=labels)

In [48]:
nba["AgeGroup"]

0      Young adults
1      Young adults
2      Early adults
3      Young adults
4      Early adults
           ...
452    Young adults
453    Early adults
454    Young adults
455    Early adults
456    Early adults
Name: AgeGroup, Length: 457, dtype: category
Categories (4, object): ['Young adults' < 'Early adults' < 'Mid adults' < 'Mature adults']

In [49]:
nba["AgeGroup"].value_counts()

AgeGroup
Young adults     197
Early adults     189
Mid adults        56
Mature adults     13
Name: count, dtype: int64